version: '3.8'

services:
  web:
    build: ./django-housing
    command: bash -c "wait-for-it db:5432 -- python manage.py runserver 0.0.0.0:8000"
    volumes: 
      - ./django-housing/:/usr/src/django-housing/
    ports: 
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
    networks:
      - housing_network

  db: 
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespassword
      - POSTGRES_DB=djangobnb
    networks:
      - housing_network

volumes:
  postgres_data:

networks:
  housing_network:
    driver: bridge
