# Generated by Django 5.1.3 on 2024-12-01 13:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_property_bathrooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/properties/additionnal_images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additionnal_images', to='property.property')),
            ],
            options={
                'verbose_name': 'Property Image',
                'verbose_name_plural': 'Properti Images',
            },
        ),
    ]
