# Generated by Django 5.1.3 on 2024-12-02 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_propertyimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyimage',
            options={'verbose_name': 'Property Image', 'verbose_name_plural': 'Property Images'},
        ),
    ]
